#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-0 --primary --mode 1920x1080 --rotate normal --output DP-4 --mode 1920x1080 --rotate normal --right-of DP-0

bspc monitor DP-0 -d ❶ ❷ ❸ ❹ ❺ 
bspc monitor DP-4 -d ❻ ❼ ❽ ❾ ❿

bspc config border_width         5
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config top_padding 0

. "${HOME}/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color3"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/heneos/HeNeos/Images/nadeko2_ai_vectorized.png
~/.config/polybar/./launch.sh
xinput --set-prop pointer:'Razer Razer DeathAdder Essential' 'libinput Accel Speed' -0.48
picom --experimental-backends &
xsetroot -cursor_name left_ptr &
