#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d ❶ ❷ ❸ ❹ ❺ ❻ ❼ ❽ ❾ ❿

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 35

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#set your wallpaper upon logging in &

feh --bg-fill /home/heneos/Descargas/bluew.png &

#This invokes pywal with your image simply replace the path

wal -i home/heneos/Descargas/bluew.png &

#source the colors located within a shell script from your cache (you don't need to touch this).

. "${HOME}/.cache/wal/colors.sh"

#Set the border colors for your windows for focused, active and inactive ones.

bspc config normal_border_color "$color1"

bspc config active_border_color "$color2"

bspc config focused_border_color "$color15"

#Use the line below if you are on bspwm >= 0.9.4

bspc config presel_feedback_color "$color1"

#Use the line below if you are on bspwm < 0.9.4

#bspc config presel_border_color "$color1"

#place the focus on where the mouse is; if you like clicking windows to focus, comment this line

bspc config focus_follows_pointer true

~/.config/polybar/launch.sh

compton -b --config ~/.config/compton/compton.conf
#~/.config/polybar/launch2.sh

