--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/heneos/HeNeos/Images/nadeko2_ai_vectorized.png"

-- Special
background="#0F0915"
foreground="#c7b0c0"
cursor="#c7b0c0"

-- Colors
color0="#0F0915"
color1="#B36431"
color2="#D1AE4D"
color3="#D8B44A"
color4="#1A1683"
color5="#211A80"
color6="#615191"
color7="#c7b0c0"
color8="#8b7b86"
color9="#B36431"
color10="#D1AE4D"
color11="#D8B44A"
color12="#1A1683"
color13="#211A80"
color14="#615191"
color15="#c7b0c0"
