# Shell variables
# Generated by 'wal'
wallpaper="/home/heneos/HeNeos/Images/nadeko2_ai_vectorized.png"

# Special
background='#0F0915'
foreground='#c7b0c0'
cursor='#c7b0c0'

# Colors
color0='#0F0915'
color1='#B36431'
color2='#D1AE4D'
color3='#D8B44A'
color4='#1A1683'
color5='#211A80'
color6='#615191'
color7='#c7b0c0'
color8='#8b7b86'
color9='#B36431'
color10='#D1AE4D'
color11='#D8B44A'
color12='#1A1683'
color13='#211A80'
color14='#615191'
color15='#c7b0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
